# Generated by Django 4.2.30 on 2026-05-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='proof_of_payment',
            field=models.ImageField(blank=True, null=True, upload_to='payments/proofs/'),
        ),
    ]
