# Generated by Django 5.2.13 on 2026-07-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.CharField(blank=True, help_text='Stripe Charge ID (ch_xxx)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Checkout Session ID (cs_xxx)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe PaymentIntent ID (pi_xxx)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_method',
            field=models.CharField(blank=True, help_text='Stripe payment method type (card, gcash, grabpay, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_receipt_url',
            field=models.URLField(blank=True, help_text='URL to the Stripe-hosted receipt', max_length=500, null=True),
        ),
    ]
