# Generated by Django 5.2.13 on 2026-07-13 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_add_stripe_fields'),
        ('reservations', '0006_cancellationrequest_cancellatio_reserva_407769_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='payments_status_db6b16_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reservation', 'status'], name='payments_reserva_36243a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['method', 'status'], name='payments_method_5d17d7_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment', 'status'], name='refunds_payment_908281_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status', '-requested_at'], name='refunds_status_32a964_idx'),
        ),
    ]
