# Generated by Django 6.0.7 on 2026-08-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_payments_status_db6b16_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(blank=True, choices=[('gcash', 'GCash'), ('maya', 'Maya'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('card', 'Credit/Debit Card')], max_length=20, null=True),
        ),
    ]
