# Generated by Django 5.2.13 on 2026-07-09 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_court_organization_site_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteCourt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='courts.court')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_courts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Court',
                'verbose_name_plural': 'Favorite Courts',
                'db_table': 'favorite_courts',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'court')},
            },
        ),
    ]
