# Generated by Django 5.2.13 on 2026-07-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_favoritecourt'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='surface_type',
            field=models.CharField(blank=True, choices=[('acrylic', 'Acrylic'), ('concrete', 'Concrete'), ('asphalt', 'Asphalt'), ('turf', 'Turf'), ('wood', 'Wood'), ('rubber', 'Rubber'), ('other', 'Other')], help_text='Court surface material', max_length=20, null=True),
        ),
    ]
