# Generated by Django 5.2.13 on 2026-07-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0004_court_surface_type'),
        ('organizations', '0006_organization_organizatio_status_984885_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['organization', 'is_active'], name='courts_organiz_c188f2_idx'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['status', 'is_active'], name='courts_status_74dd0d_idx'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['court_type', 'is_active'], name='courts_court_t_dc2c2b_idx'),
        ),
    ]
