# Generated by Django 4.2.30 on 2026-04-28 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentrental',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentrental',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_rentals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentrental',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='RentalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('method', models.CharField(blank=True, choices=[('gcash', 'GCash'), ('cash', 'Cash'), ('card', 'Credit/Debit Card')], max_length=20, null=True)),
                ('gcash_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('gcash_proof_image', models.ImageField(blank=True, null=True, upload_to='payments/gcash/rentals/')),
                ('cash_received_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payment_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_cash_payments_received', to=settings.AUTH_USER_MODEL)),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='equipment.equipmentrental')),
            ],
            options={
                'db_table': 'rental_payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
