# Generated by Django 5.2.13 on 2026-07-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='storage_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
