# Generated by Django 5.2.13 on 2026-07-13 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_model_name_equipment_notes_and_more'),
        ('organizations', '0006_organization_organizatio_status_984885_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['organization', 'is_active'], name='equipment_organiz_5f5016_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['type', 'is_active'], name='equipment_type_3ddffb_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['condition', 'is_active'], name='equipment_conditi_4d1347_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentrental',
            index=models.Index(fields=['equipment', 'status'], name='equipment_r_equipme_761f62_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentrental',
            index=models.Index(fields=['rented_by', 'status'], name='equipment_r_rented__e4674d_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentrental',
            index=models.Index(fields=['reserved_date', 'status'], name='equipment_r_reserve_1b9400_idx'),
        ),
    ]
