# Generated by Django 4.2.30 on 2026-04-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_add_rental_payment_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentrental',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
