# Generated by Django 5.2.13 on 2026-07-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_add_operating_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate from map picker', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='location_address',
            field=models.TextField(blank=True, help_text='Full address resolved from map coordinates', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate from map picker', max_digits=9, null=True),
        ),
    ]
