# Generated by Django 5.2.13 on 2026-07-09 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_latitude_organization_location_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified organizations get a badge on their public profile'),
        ),
        migrations.AddField(
            model_name='organization',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrganizationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Organization Created'), ('approved', 'Organization Approved'), ('rejected', 'Organization Rejected'), ('suspended', 'Organization Suspended'), ('reactivated', 'Organization Reactivated'), ('verified', 'Organization Verified'), ('unverified', 'Organization Unverified'), ('updated', 'Organization Updated'), ('status_changed', 'Status Changed'), ('admin_assigned', 'Org Admin Assigned'), ('admin_removed', 'Org Admin Removed'), ('staff_added', 'Staff Added'), ('staff_removed', 'Staff Removed'), ('deleted', 'Organization Deleted'), ('settings_changed', 'Settings Changed'), ('other', 'Other')], max_length=30)),
                ('details', models.TextField(blank=True, help_text='Description of what was done', null=True)),
                ('changes', models.JSONField(blank=True, help_text='JSON with before/after values of changed fields', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organizations.organization')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Audit Log',
                'verbose_name_plural': 'Organization Audit Logs',
                'db_table': 'organization_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='organizatio_organiz_acf8f6_idx'), models.Index(fields=['action', '-created_at'], name='organizatio_action_741b58_idx')],
            },
        ),
    ]
