# Generated by Django 5.2.13 on 2026-07-13 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_add_verification_and_audit_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['status', 'is_active'], name='organizatio_status_984885_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['city', 'is_active'], name='organizatio_city_cc9257_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['-created_at'], name='organizatio_created_7f4ee3_idx'),
        ),
    ]
