# Generated by Django 6.0.7 on 2026-08-05 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organization_organizatio_status_984885_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcash_number', models.CharField(blank=True, help_text='GCash mobile number shown to users when paying', max_length=20, null=True)),
                ('gcash_account_name', models.CharField(blank=True, help_text='Name registered on the GCash account', max_length=100, null=True)),
                ('maya_number', models.CharField(blank=True, help_text='Maya mobile number shown to users when paying', max_length=20, null=True)),
                ('maya_account_name', models.CharField(blank=True, help_text='Name registered on the Maya account', max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, help_text='e.g. BDO, BPI, UnionBank', max_length=100, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('qr_code', models.ImageField(blank=True, help_text='QR code image for payments (shown on the checkout page)', null=True, upload_to='organizations/payment_qr/')),
                ('payment_instructions', models.TextField(blank=True, help_text='Step-by-step instructions shown to users when paying', null=True)),
                ('accepted_payment_methods', models.JSONField(blank=True, default=list, help_text='Payment methods this organization accepts')),
                ('is_active', models.BooleanField(default=True, help_text='Enable online payment submissions for this organization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_settings', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Organization Payment Settings',
                'verbose_name_plural': 'Organization Payment Settings',
                'db_table': 'organization_payment_settings',
            },
        ),
    ]
