# Generated by Django 5.2.13 on 2026-07-13 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0005_court_courts_organiz_c188f2_idx_and_more'),
        ('organizations', '0006_organization_organizatio_status_984885_idx_and_more'),
        ('tournaments', '0002_tournament_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'status'], name='tournament__tournam_9dcd31_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['scheduled_date', 'status'], name='tournament__schedul_5e0090_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['court', 'scheduled_date'], name='tournament__court_i_6c5f48_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['tournament', 'status'], name='tournament__tournam_13836a_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['user', '-registered_at'], name='tournament__user_id_866a12_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['status', '-created_at'], name='tournaments_status_c6cf4a_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['organization', 'status'], name='tournaments_organiz_3f207f_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['tournament_start', 'status'], name='tournaments_tournam_6e15eb_idx'),
        ),
    ]
