# Generated by Django 4.2.30 on 2026-05-16 03:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_hours', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0.5)])),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equipment_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('match_name', models.CharField(blank=True, max_length=100, null=True)),
                ('match_format', models.CharField(default='singles', max_length=20)),
                ('game_type', models.CharField(default='friendly', max_length=20)),
                ('scoring_format', models.CharField(default='11', max_length=20)),
                ('points_per_game', models.IntegerField(default=11)),
                ('games_to_win', models.IntegerField(default=2)),
                ('win_by_two', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_rated', models.BooleanField(default=False, help_text='Whether this reservation has been rated by the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reservations', to=settings.AUTH_USER_MODEL)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='courts.court')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('rental_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rented_equipment', to='reservations.reservation')),
            ],
            options={
                'db_table': 'reservation_equipment',
            },
        ),
        migrations.CreateModel(
            name='CancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('refund_method', models.CharField(blank=True, choices=[('gcash', 'GCash'), ('paypal', 'PayPal'), ('card', 'Credit Card')], max_length=20, null=True)),
                ('gcash_number', models.CharField(blank=True, max_length=20, null=True)),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('paypal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('refund_processed', models.BooleanField(default=False)),
                ('refund_processed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cancellations', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_request', to='reservations.reservation')),
            ],
            options={
                'db_table': 'cancellation_requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='reservations.reservation')),
            ],
            options={
                'db_table': 'reservation_invitations',
                'unique_together': {('reservation', 'invited_user')},
            },
        ),
    ]
