# Generated by Django 4.2.30 on 2026-04-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='game_type',
            field=models.CharField(default='friendly', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='games_to_win',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='reservation',
            name='match_format',
            field=models.CharField(default='singles', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='match_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='points_per_game',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='reservation',
            name='scoring_format',
            field=models.CharField(default='11', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='win_by_two',
            field=models.BooleanField(default=True),
        ),
    ]
