# Generated by Django 4.2.30 on 2026-05-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellationrequest',
            name='cancellation_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cancellationrequest',
            name='deduction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cancellationrequest',
            name='deduction_percentage',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
        ),
        migrations.AddField(
            model_name='cancellationrequest',
            name='is_within_time_limit',
            field=models.BooleanField(default=True),
        ),
    ]
