# Generated by Django 4.2.30 on 2026-05-04 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_courtimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0004_add_quantity_to_rental'),
        ('reservations', '0002_reservation_game_type_reservation_games_to_win_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringBookingPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('day_of_week', models.PositiveSmallIntegerField(help_text='0=Monday, 6=Sunday')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('last_generated_date', models.DateField(blank=True, null=True)),
                ('max_reservations_ahead', models.PositiveIntegerField(default=4, help_text='How many future reservations to maintain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_patterns', to='courts.court')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recurring_booking_patterns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('corporate', 'Corporate Event'), ('birthday', 'Birthday Party'), ('tournament', 'Tournament'), ('practice', 'Team Practice'), ('social', 'Social Gathering'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('estimated_players', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('needs_equipment', models.BooleanField(default=False)),
                ('equipment_notes', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_group_bookings', to=settings.AUTH_USER_MODEL)),
                ('courts', models.ManyToManyField(related_name='group_bookings', to='courts.court')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_group_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('preferred_start_time', models.TimeField()),
                ('preferred_end_time', models.TimeField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('notified', 'Notified'), ('converted', 'Converted to Reservation'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority = earlier notification')),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Deadline to convert to reservation', null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='courts.court')),
                ('reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entry', to='reservations.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'waitlist_entries',
                'ordering': ['-priority', 'created_at'],
                'unique_together': {('user', 'court', 'date', 'preferred_start_time')},
            },
        ),
        migrations.CreateModel(
            name='ReservationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='reservations.reservation')),
            ],
            options={
                'db_table': 'reservation_invitations',
                'unique_together': {('reservation', 'invited_user')},
            },
        ),
        migrations.CreateModel(
            name='BookingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_hours', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('match_format', models.CharField(default='singles', max_length=20)),
                ('game_type', models.CharField(default='friendly', max_length=20)),
                ('scoring_format', models.CharField(default='11', max_length=20)),
                ('games_to_win', models.IntegerField(default=2)),
                ('preferred_start_time', models.TimeField(blank=True, null=True)),
                ('preferred_day_of_week', models.PositiveSmallIntegerField(blank=True, help_text='0=Monday, 6=Sunday', null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courts.court')),
                ('default_equipment', models.ManyToManyField(blank=True, related_name='booking_templates', to='equipment.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking_templates',
                'ordering': ['-is_favorite', '-usage_count', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
