# Generated by Django 4.2.30 on 2026-05-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_cancellationrequest_cancellation_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Cancellation Policy', max_length=100)),
                ('time_limit_minutes', models.PositiveIntegerField(default=20, help_text='Time limit in minutes for cancellation after reservation creation')),
                ('deduction_percentage', models.DecimalField(decimal_places=2, default=30, help_text='Percentage deduction for cancellation fee', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cancellation Policies',
                'db_table': 'cancellation_policies',
            },
        ),
    ]
