# Generated by Django 4.2.30 on 2026-05-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_recurringbookingpattern_groupbooking_waitlistentry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupbooking',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='groupbooking',
            name='courts',
        ),
        migrations.RemoveField(
            model_name='groupbooking',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='recurringbookingpattern',
            name='court',
        ),
        migrations.RemoveField(
            model_name='recurringbookingpattern',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='waitlistentry',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='court',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='user',
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_rated',
            field=models.BooleanField(default=False, help_text='Whether this reservation has been rated by the user'),
        ),
        migrations.DeleteModel(
            name='BookingTemplate',
        ),
        migrations.DeleteModel(
            name='GroupBooking',
        ),
        migrations.DeleteModel(
            name='RecurringBookingPattern',
        ),
        migrations.DeleteModel(
            name='WaitlistEntry',
        ),
    ]
