# Generated by Django 5.2.13 on 2026-07-09 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_court_organization_site_organization'),
        ('reservations', '0004_cancellationrequest_processed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('notified', 'Notified'), ('claimed', 'Claimed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('preferred_slot_only', models.BooleanField(default=True, help_text='If True, only notify for this exact time slot. If False, notify for any available slot on this date.')),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='courts.court')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'waitlist_entries',
                'ordering': ['date', 'start_time', 'created_at'],
                'indexes': [models.Index(fields=['court', 'date', 'status'], name='waitlist_en_court_i_72b4bd_idx'), models.Index(fields=['user', 'status'], name='waitlist_en_user_id_fee085_idx')],
            },
        ),
    ]
