# Generated by Django 4.2.30 on 2026-05-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_add_rating_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellationrequest',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cancellationrequest',
            name='gcash_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cancellationrequest',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cancellationrequest',
            name='refund_method',
            field=models.CharField(blank=True, choices=[('gcash', 'GCash'), ('paypal', 'PayPal'), ('card', 'Credit Card')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cancellationrequest',
            name='refund_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cancellationrequest',
            name='refund_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
