# Generated by Django 5.2.13 on 2026-07-13 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0005_court_courts_organiz_c188f2_idx_and_more'),
        ('reservations', '0005_add_waitlist_entry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cancellationrequest',
            index=models.Index(fields=['reservation', 'approved'], name='cancellatio_reserva_407769_idx'),
        ),
        migrations.AddIndex(
            model_name='cancellationrequest',
            index=models.Index(fields=['requested_by', '-requested_at'], name='cancellatio_request_f87318_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'date'], name='reservation_status_435d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user', '-created_at'], name='reservation_user_id_c22ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['court', 'date'], name='reservation_court_i_4160db_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['date', 'start_time'], name='reservation_date_42bf0a_idx'),
        ),
    ]
