# Generated by Django 6.0.7 on 2026-07-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_cancellationrequest_cancellatio_reserva_407769_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellationrequest',
            name='reason_category',
            field=models.CharField(blank=True, choices=[('change_of_plans', 'Change of Plans'), ('scheduling_conflict', 'Scheduling Conflict'), ('personal_emergency', 'Personal Emergency'), ('health_reasons', 'Health Reasons'), ('weather_conditions', 'Weather Conditions'), ('court_no_longer_needed', 'Court No Longer Needed'), ('found_another_venue', 'Found Another Venue'), ('duplicate_reservation', 'Duplicate Reservation'), ('payment_issue', 'Payment Issue'), ('booking_mistake', 'Booking Mistake'), ('transportation_problem', 'Transportation Problem'), ('tournament_cancelled', 'Tournament Cancelled'), ('other', 'Other')], help_text='Predefined reason category selected by the user', max_length=50, null=True),
        ),
    ]
