# Generated by Django 4.2.30 on 2026-05-16 03:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('hero_badge', 'Hero Badge'), ('hero_title', 'Hero Title'), ('hero_subtitle', 'Hero Subtitle'), ('mission_title', 'Mission Section Title'), ('mission_text', 'Mission Text'), ('mission_features', 'Mission Features (comma-separated)'), ('vision_title', 'Vision Section Title'), ('vision_text', 'Vision Text'), ('vision_features', 'Vision Features (comma-separated)'), ('stats_courts', 'Stats - Courts Label'), ('stats_members', 'Stats - Members Label'), ('stats_years', 'Stats - Years Label'), ('stats_tournaments', 'Stats - Tournaments Label'), ('journey_badge', 'Journey Section Badge'), ('journey_title', 'Journey Section Title'), ('journey_subtitle', 'Journey Section Subtitle'), ('team_badge', 'Team Section Badge'), ('team_title', 'Team Section Title'), ('team_subtitle', 'Team Section Subtitle'), ('facilities_badge', 'Facilities Section Badge'), ('facilities_title', 'Facilities Section Title'), ('facilities_subtitle', 'Facilities Section Subtitle'), ('why_badge', 'Why Choose Us Badge'), ('why_title', 'Why Choose Us Title'), ('why_subtitle', 'Why Choose Us Subtitle'), ('gallery_badge', 'Gallery Section Badge'), ('gallery_title', 'Gallery Section Title'), ('gallery_subtitle', 'Gallery Section Subtitle'), ('location_badge', 'Location Section Badge'), ('location_title', 'Location Section Title'), ('location_description', 'Location Description'), ('cta_title', 'CTA Section Title'), ('cta_subtitle', 'CTA Section Subtitle')], max_length=50, unique=True)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Contents',
                'ordering': ['section'],
            },
        ),
        migrations.CreateModel(
            name='AboutGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/gallery/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('alt_text', models.CharField(help_text='Alternative text for accessibility', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Gallery Image',
                'verbose_name_plural': 'About Gallery Images',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fa-check', help_text='Font Awesome icon class, e.g., fa-wifi, fa-car', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BusinessHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_range', models.CharField(help_text="e.g., 'Monday - Friday'", max_length=100)),
                ('hours', models.CharField(help_text="e.g., '6:00 AM - 10:00 PM'", max_length=100)),
                ('icon_color', models.CharField(default='primary', help_text='Bootstrap color name', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Hour',
                'verbose_name_plural': 'Business Hours',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ContactContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('hero_badge', 'Hero Badge'), ('hero_title', 'Hero Title'), ('hero_subtitle', 'Hero Subtitle'), ('phone_label', 'Phone Card Label'), ('phone_hours', 'Phone Card Hours'), ('email_label', 'Email Card Label'), ('email_response', 'Email Response Time'), ('visit_label', 'Visit Card Label'), ('visit_city', 'Visit City'), ('form_title', 'Contact Form Title'), ('form_name_label', 'Form - Name Label'), ('form_email_label', 'Form - Email Label'), ('form_subject_label', 'Form - Subject Label'), ('form_message_label', 'Form - Message Label'), ('form_submit_text', 'Form Submit Button Text'), ('hours_title', 'Business Hours Title'), ('quick_links_title', 'Quick Links Title'), ('social_title', 'Social Media Title'), ('map_badge', 'Map Section Badge'), ('map_title', 'Map Section Title'), ('map_subtitle', 'Map Section Subtitle'), ('getting_here_title', 'Getting Here Title'), ('faq_badge', 'FAQ Section Badge'), ('faq_title', 'FAQ Section Title'), ('faq_subtitle', 'FAQ Section Subtitle'), ('cta_title', 'CTA Section Title'), ('cta_subtitle', 'CTA Section Subtitle')], max_length=50, unique=True)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Page Content',
                'verbose_name_plural': 'Contact Page Contents',
                'ordering': ['section'],
            },
        ),
        migrations.CreateModel(
            name='ContactFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('icon_color', models.CharField(default='primary', help_text='Bootstrap color name', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact FAQ',
                'verbose_name_plural': 'Contact FAQs',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='09455470173', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(default='Valencia, Negros Oriental, Philippines, 6215')),
                ('city_country', models.CharField(default='Valencia, Negros Oriental, Philippines, 6215', max_length=200)),
                ('google_maps_url', models.URLField(blank=True, help_text='Google Maps directions URL', max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fa-check', help_text='Font Awesome icon class', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('color', models.CharField(default='primary', help_text='Bootstrap color name', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('alt_text', models.CharField(help_text='Alternative text for accessibility', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('hero_title', 'Hero Title'), ('hero_subtitle', 'Hero Subtitle'), ('about_title', 'About Section Title'), ('about_text', 'About Section Text'), ('cta_title', 'CTA Section Title'), ('cta_text', 'CTA Section Text')], max_length=50, unique=True)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page Content',
                'verbose_name_plural': 'Home Page Contents',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('color', models.CharField(default='primary', help_text='Bootstrap color name: primary, success, warning, info, danger', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
                'ordering': ['display_order', 'year'],
            },
        ),
        migrations.CreateModel(
            name='PricingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('hero_badge', 'Hero Badge'), ('hero_title', 'Hero Title'), ('hero_subtitle', 'Hero Subtitle'), ('court_rates_title', 'Court Rates Section Title'), ('court_rates_subtitle', 'Court Rates Section Subtitle'), ('membership_title', 'Membership Section Title'), ('membership_subtitle', 'Membership Section Subtitle'), ('comparison_title', 'Comparison Table Title'), ('comparison_subtitle', 'Comparison Table Subtitle'), ('services_title', 'Additional Services Title'), ('services_subtitle', 'Additional Services Subtitle'), ('faq_title', 'FAQ Section Title'), ('faq_subtitle', 'FAQ Section Subtitle'), ('cta_title', 'CTA Section Title'), ('cta_subtitle', 'CTA Section Subtitle')], max_length=50, unique=True)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Page Content',
                'verbose_name_plural': 'Pricing Page Contents',
                'ordering': ['section'],
            },
        ),
        migrations.CreateModel(
            name='PricingFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing FAQ',
                'verbose_name_plural': 'Pricing FAQs',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('period', models.CharField(blank=True, help_text="e.g., 'month', 'year', or leave blank for one-time", max_length=50)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(default=list, help_text='List of features as strings')),
                ('is_recommended', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Tier',
                'verbose_name_plural': 'Pricing Tiers',
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok')], max_length=50)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['display_order', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('color', models.CharField(default='primary', help_text='Bootstrap color name for styling', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fa-check', help_text='Font Awesome icon class', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('color', models.CharField(default='primary', help_text='Bootstrap color name', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Why Choose Item',
                'verbose_name_plural': 'Why Choose Items',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='e.g., Regular Member, Tournament Player', max_length=100)),
                ('rating', models.IntegerField(default=5, help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField(help_text='Testimonial content')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Only approved testimonials are displayed on the homepage')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='The user who submitted this testimonial (if user-submitted)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('general_inquiry', 'General Inquiry'), ('booking', 'Booking Related'), ('feedback', 'Feedback'), ('support', 'Technical Support'), ('partnership', 'Partnership'), ('other', 'Other')], default='general_inquiry', max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=20)),
                ('admin_reply', models.TextField(blank=True, help_text="Admin's reply to this message", null=True)),
                ('replied_at', models.DateTimeField(blank=True, help_text='When the admin replied', null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether admin has read this message')),
                ('user_read_reply', models.BooleanField(default=False, help_text="Whether user has read the admin's reply")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replied_by', models.ForeignKey(blank=True, help_text='Admin user who replied', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5, help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Optional comment (max 500 characters)', max_length=500, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured ratings are displayed on the homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.ForeignKey(help_text='The completed reservation being rated', on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='reservations.reservation')),
                ('user', models.ForeignKey(help_text='The user who submitted this rating', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'reservation')},
            },
        ),
    ]
