# Generated by Django 5.2.13 on 2026-07-09 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_courtpagesettings_equipmentcategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='fa-question-circle', help_text='Font Awesome icon class', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'verbose_name_plural': 'FAQ Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FAQPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('hero_badge', 'Hero Badge'), ('hero_title', 'Hero Title'), ('hero_subtitle', 'Hero Subtitle'), ('search_placeholder', 'Search Placeholder Text'), ('contact_title', 'Still Need Help Title'), ('contact_text', 'Still Need Help Text'), ('cta_button_text', 'CTA Button Text')], max_length=50, unique=True)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ Page Content',
                'verbose_name_plural': 'FAQ Page Contents',
                'ordering': ['section'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('hero_badge', 'Hero Badge'), ('hero_title', 'Hero Title'), ('hero_subtitle', 'Hero Subtitle'), ('last_updated_text', 'Last Updated Label'), ('contact_email', 'Contact Email'), ('contact_phone', 'Contact Phone'), ('contact_address', 'Contact Address')], max_length=50, unique=True)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Privacy Policy Content',
                'verbose_name_plural': 'Privacy Policy Contents',
                'ordering': ['section'],
            },
        ),
        migrations.CreateModel(
            name='PrivacySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('icon', models.CharField(default='fa-shield-alt', help_text='Font Awesome icon class', max_length=50)),
                ('icon_color', models.CharField(default='primary', help_text='Bootstrap color name', max_length=50)),
                ('section_number', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Privacy Policy Section',
                'verbose_name_plural': 'Privacy Policy Sections',
                'ordering': ['section_number'],
            },
        ),
        migrations.CreateModel(
            name='TermsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('hero_badge', 'Hero Badge'), ('hero_title', 'Hero Title'), ('hero_subtitle', 'Hero Subtitle'), ('last_updated_text', 'Last Updated Label'), ('contact_email', 'Contact Email'), ('contact_phone', 'Contact Phone'), ('contact_address', 'Contact Address')], max_length=50, unique=True)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Terms of Service Content',
                'verbose_name_plural': 'Terms of Service Contents',
                'ordering': ['section'],
            },
        ),
        migrations.CreateModel(
            name='TermsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('icon', models.CharField(default='fa-file-contract', help_text='Font Awesome icon class', max_length=50)),
                ('icon_color', models.CharField(default='primary', help_text='Bootstrap color name', max_length=50)),
                ('section_number', models.PositiveIntegerField(default=1, help_text='Section number (1, 2, 3...) for ordering')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Terms of Service Section',
                'verbose_name_plural': 'Terms of Service Sections',
                'ordering': ['section_number'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dashboard.faqcategory')),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'verbose_name_plural': 'FAQ Items',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Display name for the file', max_length=200)),
                ('file', models.FileField(upload_to='media_library/%Y/%m/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('other', 'Other')], default='image', max_length=20)),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=300)),
                ('caption', models.TextField(blank=True, help_text='Optional caption')),
                ('file_size', models.PositiveIntegerField(default=0, editable=False, help_text='File size in bytes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media Library Item',
                'verbose_name_plural': 'Media Library',
                'ordering': ['-created_at'],
            },
        ),
    ]
