# Generated by Django 4.2.30 on 2026-05-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_add_testimonial_approval_and_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Google Maps directions URL', max_length=1000),
        ),
    ]
