# Generated by Django 4.2.30 on 2026-05-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_contactinfo_google_maps_url_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.TextField(default='Valencia, Negros Oriental, Philippines, 6215'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='city_country',
            field=models.CharField(default='Valencia, Negros Oriental, Philippines, 6215', max_length=200),
        ),
    ]
