# Generated by Django 4.2.30 on 2026-05-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_update_contactinfo_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(default='09455470173', max_length=100),
        ),
    ]
