# Generated by Django 4.2.30 on 2026-05-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_update_phone_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(default='picklespehere@gmail.com', max_length=254),
        ),
    ]
