# Generated by Django 4.2.30 on 2026-05-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_email_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_operating', models.PositiveIntegerField(default=3)),
                ('tournaments_hosted', models.PositiveIntegerField(default=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page Stats',
                'verbose_name_plural': 'About Page Stats',
            },
        ),
    ]
