# Generated by Django 4.2.30 on 2026-05-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_add_aboutstats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutStats',
        ),
    ]
