# Generated by Django 4.2.30 on 2026-05-06 15:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0004_add_rating_system'),
        ('dashboard', '0011_auto_approve_testimonials_and_optional_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Testimonial (Deprecated)', 'verbose_name_plural': 'Testimonials (Deprecated)'},
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Only approved testimonials are displayed on the homepage'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=models.TextField(help_text='Testimonial content'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5, help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Optional comment (max 500 characters)', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.ForeignKey(help_text='The completed reservation being rated', on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='reservations.reservation')),
                ('user', models.ForeignKey(help_text='The user who submitted this rating', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'reservation')},
            },
        ),
    ]
