# Generated by Django 4.2.30 on 2026-05-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_add_rating_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AddField(
            model_name='rating',
            name='featured_at',
            field=models.DateTimeField(blank=True, help_text='When this rating was featured on homepage', null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Display this rating on the homepage'),
        ),
    ]
