# Generated by Django 4.2.30 on 2026-05-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_testimonial_options_rating_featured_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='featured_at',
        ),
        migrations.AlterField(
            model_name='rating',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured ratings appear on the homepage'),
        ),
    ]
