# Generated by Django 4.2.30 on 2026-05-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_add_rating_is_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.AlterField(
            model_name='rating',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured ratings appear first on the homepage'),
        ),
    ]
