# Generated by Django 4.2.30 on 2026-05-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_rating_options_alter_rating_is_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='rating',
            name='display_on_homepage',
            field=models.BooleanField(default=True, help_text='Show this rating on the homepage. Uncheck to hide specific ratings.'),
        ),
    ]
