# Generated by Django 4.2.30 on 2026-05-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_add_rating_display_on_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='display_on_homepage',
        ),
        migrations.AddField(
            model_name='rating',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured ratings are displayed on the homepage'),
        ),
    ]
