# Generated by Django 4.2.30 on 2026-05-07 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0017_add_featured_to_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('general_inquiry', 'General Inquiry'), ('booking', 'Booking Related'), ('feedback', 'Feedback'), ('support', 'Technical Support'), ('partnership', 'Partnership'), ('other', 'Other')], default='general_inquiry', max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=20)),
                ('admin_reply', models.TextField(blank=True, help_text="Admin's reply to this message", null=True)),
                ('replied_at', models.DateTimeField(blank=True, help_text='When the admin replied', null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether admin has read this message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replied_by', models.ForeignKey(blank=True, help_text='Admin user who replied', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
