# Generated by Django 4.2.30 on 2026-05-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='user_read_reply',
            field=models.BooleanField(default=False, help_text="Whether user has read the admin's reply"),
        ),
    ]
