# Generated by Django 4.2.30 on 2026-05-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_contactmessage_user_read_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/gallery/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('alt_text', models.CharField(help_text='Alternative text for accessibility', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Gallery Image',
                'verbose_name_plural': 'About Gallery Images',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
