# Generated by Django 4.2.30 on 2026-05-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell others about your playing style and availability', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='looking_for_matches',
            field=models.BooleanField(default=False, help_text='Visible to others looking for players'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_play_times',
            field=models.JSONField(blank=True, default=dict, help_text="e.g., {'weekday_evenings': true, 'weekend_mornings': true}"),
        ),
        migrations.AddField(
            model_name='user',
            name='skill_level',
            field=models.CharField(choices=[('beginner', 'Beginner (1.0-2.5)'), ('intermediate', 'Intermediate (3.0-3.5)'), ('advanced', 'Advanced (4.0-4.5)'), ('expert', 'Expert (5.0+)')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='skill_rating',
            field=models.DecimalField(decimal_places=1, default=2.5, help_text='Pickleball skill rating 1.0-5.0+', max_digits=3),
        ),
    ]
