# Generated by Django 4.2.30 on 2026-05-07 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_bio_user_looking_for_matches_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='looking_for_matches',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_play_times',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skill_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skill_rating',
        ),
    ]
