# Generated by Django 5.2.13 on 2026-07-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_latitude_user_longitude'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0006_organization_organizatio_status_984885_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='users_role_a8f2ba_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-created_at'], name='users_created_30b417_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'role'], name='users_organiz_6045b8_idx'),
        ),
    ]
