# Generated by Django 6.0.7 on 2026-07-21 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_users_role_a8f2ba_idx_and_more'),
        ('organizations', '0006_organization_organizatio_status_984885_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text='Department or division', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Middle Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about this staff member', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_id',
            field=models.CharField(blank=True, help_text='Unique staff identifier', max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='StaffPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manage_reservations', models.BooleanField(default=True)),
                ('manage_payments', models.BooleanField(default=False)),
                ('manage_refunds', models.BooleanField(default=False)),
                ('manage_equipment', models.BooleanField(default=True)),
                ('manage_tournaments', models.BooleanField(default=False)),
                ('manage_notifications', models.BooleanField(default=True)),
                ('view_reports', models.BooleanField(default=False)),
                ('manage_courts', models.BooleanField(default=False)),
                ('manage_sites', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_permissions', to='organizations.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Permission',
                'verbose_name_plural': 'Staff Permissions',
                'db_table': 'staff_permissions',
            },
        ),
    ]
