# Generated by Django 6.0.7 on 2026-07-21 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_staff_fields_and_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffpermission',
            name='organization',
        ),
    ]
