# Generated by Django 4.2.30 on 2026-04-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Match Settings', max_length=100)),
                ('format', models.CharField(choices=[('singles', 'Singles'), ('doubles', 'Doubles')], default='singles', max_length=20)),
                ('games_to_win', models.IntegerField(default=2)),
                ('points_per_game', models.IntegerField(default=11)),
                ('win_by_two', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'match_settings',
            },
        ),
    ]
