# Generated by Django 5.2.13 on 2026-07-06 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_create_default_org'),
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchsettings',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_settings', to='organizations.organization'),
        ),
    ]
