# Generated by Django 5.2.13 on 2026-07-13 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_cancellationrequest_cancellatio_reserva_407769_idx_and_more'),
        ('scoring', '0002_add_org_to_match_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status', '-created_at'], name='matches_status_d87aa1_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['reservation'], name='matches_reserva_f7eaa3_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstats',
            index=models.Index(fields=['-wins', '-total_matches'], name='player_stat_wins_1ee3e5_idx'),
        ),
    ]
