# Generated by Django 5.2.13 on 2026-07-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_match_matches_status_d87aa1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game_type',
            field=models.CharField(default='friendly', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='match_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='scoring_format',
            field=models.CharField(default='11', max_length=20),
        ),
    ]
