# Generated by Django 4.2.30 on 2026-04-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_matchsettings_game_type_matchsettings_scoring_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game_type',
            field=models.CharField(choices=[('friendly', 'Friendly Match'), ('ranked', 'Ranked Match'), ('practice', 'Practice Match')], default='friendly', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='scoring_format',
            field=models.CharField(choices=[('11', '11 Points'), ('15', '15 Points'), ('21', '21 Points'), ('best_of_3', 'Best of 3 Games')], default='11', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='format',
            field=models.CharField(choices=[('singles', 'Singles (1 vs 1)'), ('doubles', 'Doubles (2 vs 2)'), ('mixed_doubles', 'Mixed Doubles (1M + 1F)')], default='singles', max_length=20),
        ),
        migrations.AlterField(
            model_name='matchsettings',
            name='scoring_format',
            field=models.CharField(choices=[('11', '11 Points'), ('15', '15 Points'), ('21', '21 Points'), ('best_of_3', 'Best of 3 Games')], default='11', max_length=20),
        ),
    ]
