# Generated by Django 5.2.13 on 2026-07-29 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_match_game_type_match_match_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.IntegerField(choices=[(1, 'Team 1'), (2, 'Team 2')])),
                ('player_number', models.IntegerField(choices=[(1, 'Player 1'), (2, 'Player 2')], default=1)),
                ('full_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_players', to='scoring.match')),
            ],
            options={
                'verbose_name': 'Guest Player',
                'verbose_name_plural': 'Guest Players',
                'db_table': 'guest_players',
            },
        ),
    ]
