# Generated by Django 4.2.30 on 2026-04-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_match_game_type_match_scoring_format_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='scoring_format',
        ),
        migrations.RemoveField(
            model_name='matchsettings',
            name='scoring_format',
        ),
        migrations.AlterField(
            model_name='match',
            name='format',
            field=models.CharField(choices=[('singles', 'Singles (1 vs 1)'), ('doubles', 'Doubles (2 vs 2)'), ('mixed_doubles', 'Mixed Doubles')], default='doubles', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='game_type',
            field=models.CharField(choices=[('friendly', 'Friendly'), ('ranked', 'Ranked'), ('practice', 'Practice')], default='friendly', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='games_to_win',
            field=models.IntegerField(choices=[(1, '1 Game'), (2, 'Best of 3'), (3, 'Best of 5')], default=2),
        ),
        migrations.AlterField(
            model_name='match',
            name='points_per_game',
            field=models.IntegerField(choices=[(11, '11 Points'), (15, '15 Points'), (21, '21 Points')], default=11),
        ),
        migrations.AlterField(
            model_name='matchsettings',
            name='format',
            field=models.CharField(choices=[('singles', 'Singles (1 vs 1)'), ('doubles', 'Doubles (2 vs 2)'), ('mixed_doubles', 'Mixed Doubles')], default='doubles', max_length=20),
        ),
        migrations.AlterField(
            model_name='matchsettings',
            name='game_type',
            field=models.CharField(choices=[('friendly', 'Friendly'), ('ranked', 'Ranked'), ('practice', 'Practice')], default='friendly', max_length=20),
        ),
        migrations.AlterField(
            model_name='matchsettings',
            name='games_to_win',
            field=models.IntegerField(choices=[(1, '1 Game'), (2, 'Best of 3'), (3, 'Best of 5')], default=2),
        ),
        migrations.AlterField(
            model_name='matchsettings',
            name='points_per_game',
            field=models.IntegerField(choices=[(11, '11 Points'), (15, '15 Points'), (21, '21 Points')], default=11),
        ),
    ]
