# Generated by Django 5.2.13 on 2026-07-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0005_guestplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
