# Generated by Django 4.2.30 on 2026-04-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0005_remove_match_scoring_format_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='game_type',
        ),
        migrations.AddField(
            model_name='matchsettings',
            name='scoring_format',
            field=models.CharField(choices=[('11', '11 Points (Standard)'), ('15', '15 Points (Extended)'), ('21', '21 Points (Extended)'), ('best_of_3', 'Best of 3 Games')], default='11', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='format',
            field=models.CharField(default='singles', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='games_to_win',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='match',
            name='points_per_game',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='matchsettings',
            name='format',
            field=models.CharField(choices=[('singles', 'Singles'), ('doubles', 'Doubles'), ('mixed_doubles', 'Mixed Doubles')], default='singles', max_length=20),
        ),
        migrations.AlterField(
            model_name='matchsettings',
            name='games_to_win',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='matchsettings',
            name='points_per_game',
            field=models.IntegerField(default=11),
        ),
    ]
