# Generated by Django 4.2.30 on 2026-04-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0006_remove_match_game_type_matchsettings_scoring_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='format',
            field=models.CharField(choices=[('singles', 'Singles'), ('doubles', 'Doubles'), ('mixed_doubles', 'Mixed Doubles')], default='singles', max_length=20),
        ),
    ]
