# Generated by Django 4.2.30 on 2026-05-04 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0003_recurringbookingpattern_groupbooking_waitlistentry_and_more'),
        ('scoring', '0007_add_format_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('matches_played', 'Matches Played'), ('matches_won', 'Matches Won'), ('tournaments_played', 'Tournaments Played'), ('tournaments_won', 'Tournaments Won'), ('games_played', 'Games Played'), ('skill_rating', 'Achieve Skill Rating'), ('streak', 'Win Streak'), ('play_time', 'Total Play Time (hours)'), ('specific_opponent', 'Beat Specific Opponent'), ('consecutive_days', 'Consecutive Play Days')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_value', models.PositiveIntegerField(default=1)),
                ('current_value', models.PositiveIntegerField(default=0)),
                ('period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='monthly', max_length=20)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('is_public', models.BooleanField(default=True, help_text='Visible to friends')),
                ('reward_points', models.PositiveIntegerField(default=0, help_text='Loyalty points awarded on completion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
                ('specific_opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'player_goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_type', models.CharField(choices=[('full_match', 'Full Match'), ('highlights', 'Highlights'), ('training', 'Training Session'), ('analysis', 'Analysis/Replay')], default='full_match', max_length=20)),
                ('privacy', models.CharField(choices=[('private', 'Private - Only Me'), ('friends', 'Friends Only'), ('public', 'Public'), ('shared', 'Shared with Participants')], default='shared', max_length=20)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='match_videos/')),
                ('external_url', models.URLField(blank=True, help_text='YouTube/Vimeo link if not uploaded directly', null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='match_videos/thumbnails/')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size_mb', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_videos', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='scoring.match')),
                ('participants', models.ManyToManyField(blank=True, related_name='videos_appearing_in', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='reservations.reservation')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'match_videos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('general', 'General Notes'), ('technical', 'Technical Analysis'), ('strategy', 'Strategy Notes'), ('improvement', 'Areas to Improve'), ('opponent', 'Opponent Notes')], default='general', max_length=20)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=True, help_text='Only visible to author')),
                ('video_timestamp', models.PositiveIntegerField(blank=True, help_text='Seconds into video', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_notes', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notes', to='scoring.match')),
            ],
            options={
                'db_table': 'match_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeadToHeadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_matches', models.PositiveIntegerField(default=0)),
                ('player1_wins', models.PositiveIntegerField(default=0)),
                ('player2_wins', models.PositiveIntegerField(default=0)),
                ('last_match_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_match_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_h2h_wins', to=settings.AUTH_USER_MODEL)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h2h_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h2h_as_player2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'head_to_head_records',
                'unique_together': {('player1', 'player2')},
            },
        ),
    ]
