# Generated by Django 4.2.30 on 2026-05-07 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0008_playergoal_matchvideo_matchnote_headtoheadrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchnote',
            name='author',
        ),
        migrations.RemoveField(
            model_name='matchnote',
            name='match',
        ),
        migrations.RemoveField(
            model_name='matchvideo',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='matchvideo',
            name='match',
        ),
        migrations.RemoveField(
            model_name='matchvideo',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='matchvideo',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='matchvideo',
            name='uploader',
        ),
        migrations.RemoveField(
            model_name='playergoal',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playergoal',
            name='specific_opponent',
        ),
        migrations.DeleteModel(
            name='HeadToHeadRecord',
        ),
        migrations.DeleteModel(
            name='MatchNote',
        ),
        migrations.DeleteModel(
            name='MatchVideo',
        ),
        migrations.DeleteModel(
            name='PlayerGoal',
        ),
    ]
