# Generated by Django 5.2.13 on 2026-07-08 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0002_equipment_organization'),
        ('organizations', '0004_organization_latitude_organization_location_address_and_more'),
        ('payments', '0005_alter_payment_status'),
        ('reservations', '0004_cancellationrequest_processed_by'),
        ('scoring', '0002_add_org_to_match_settings'),
        ('tournaments', '0002_tournament_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('title_template', models.CharField(help_text='Use {variable} placeholders', max_length=200)),
                ('message_template', models.TextField(help_text='Use {variable} placeholders for dynamic content')),
                ('notification_type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('category', models.CharField(choices=[('reservation', 'Reservations'), ('payment', 'Payments'), ('refund', 'Refunds'), ('cancellation', 'Cancellations'), ('tournament', 'Tournaments'), ('equipment', 'Equipment'), ('organization', 'Organizations'), ('staff', 'Staff'), ('user', 'Users'), ('report', 'Reports'), ('system', 'System'), ('security', 'Security'), ('maintenance', 'Maintenance'), ('announcement', 'Announcements'), ('promotion', 'Promotions'), ('message', 'Messages'), ('account', 'Account')], default='system', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('scheduled', 'Scheduled')], default='draft', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('target_roles', models.JSONField(blank=True, default=list)),
                ('target_type', models.CharField(choices=[('all', 'All Users'), ('roles', 'Specific Roles'), ('organization', 'Specific Organization'), ('users', 'Specific Users')], default='all', max_length=20)),
                ('notification_type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('category', models.CharField(choices=[('reservation', 'Reservations'), ('payment', 'Payments'), ('refund', 'Refunds'), ('cancellation', 'Cancellations'), ('tournament', 'Tournaments'), ('equipment', 'Equipment'), ('organization', 'Organizations'), ('staff', 'Staff'), ('user', 'Users'), ('report', 'Reports'), ('system', 'System'), ('security', 'Security'), ('maintenance', 'Maintenance'), ('announcement', 'Announcements'), ('promotion', 'Promotions'), ('message', 'Messages'), ('account', 'Account')], default='announcement', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('recipient_count', models.IntegerField(default=0)),
                ('read_count', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to=settings.AUTH_USER_MODEL)),
                ('target_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization')),
                ('target_users', models.ManyToManyField(blank=True, related_name='targeted_broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'broadcast_messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_reservation', models.BooleanField(default=True)),
                ('notify_payment', models.BooleanField(default=True)),
                ('notify_refund', models.BooleanField(default=True)),
                ('notify_cancellation', models.BooleanField(default=True)),
                ('notify_tournament', models.BooleanField(default=True)),
                ('notify_equipment', models.BooleanField(default=True)),
                ('notify_organization', models.BooleanField(default=True)),
                ('notify_staff', models.BooleanField(default=True)),
                ('notify_user', models.BooleanField(default=True)),
                ('notify_report', models.BooleanField(default=False)),
                ('notify_system', models.BooleanField(default=True)),
                ('notify_security', models.BooleanField(default=True)),
                ('notify_maintenance', models.BooleanField(default=True)),
                ('notify_announcement', models.BooleanField(default=True)),
                ('notify_promotion', models.BooleanField(default=False)),
                ('notify_message', models.BooleanField(default=True)),
                ('notify_account', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=False)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('in_app_notifications', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('instant', 'Instant'), ('hourly', 'Hourly Digest'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='instant', max_length=10)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('category', models.CharField(choices=[('reservation', 'Reservations'), ('payment', 'Payments'), ('refund', 'Refunds'), ('cancellation', 'Cancellations'), ('tournament', 'Tournaments'), ('equipment', 'Equipment'), ('organization', 'Organizations'), ('staff', 'Staff'), ('user', 'Users'), ('report', 'Reports'), ('system', 'System'), ('security', 'Security'), ('maintenance', 'Maintenance'), ('announcement', 'Announcements'), ('promotion', 'Promotions'), ('message', 'Messages'), ('account', 'Account')], default='system', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, help_text='URL to redirect when clicked', max_length=500)),
                ('action_text', models.CharField(blank=True, default='View Details', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('related_equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.equipment')),
                ('related_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoring.match')),
                ('related_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization')),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment')),
                ('related_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.reservation')),
                ('related_tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'), models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_c4e471_idx'), models.Index(fields=['user', 'category', '-created_at'], name='notificatio_user_id_2b1ddd_idx'), models.Index(fields=['user', 'priority', '-created_at'], name='notificatio_user_id_316243_idx')],
            },
        ),
    ]
