# Generated by Django 5.2.13 on 2026-07-15 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmtpConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.EmailField(blank=True, default='', max_length=255)),
                ('smtp_password', models.CharField(blank=True, default='', help_text='SMTP password or app password', max_length=500)),
                ('encryption', models.CharField(choices=[('tls', 'TLS'), ('ssl', 'SSL'), ('none', 'None')], default='tls', max_length=10)),
                ('sender_name', models.CharField(default='PickleSphere', max_length=255)),
                ('sender_email', models.EmailField(default='noreply@picklesphere.com', max_length=255)),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMTP Configuration',
                'verbose_name_plural': 'SMTP Configurations',
                'db_table': 'smtp_configurations',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('body_preview', models.TextField(blank=True, help_text='Plain text preview of email body')),
                ('email_type', models.CharField(blank=True, default='', help_text='e.g. welcome, password_reset, reservation_confirmed', max_length=100)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('related_object_id', models.CharField(blank=True, help_text='ID of related model (e.g. reservation ID)', max_length=50, null=True)),
                ('related_object_type', models.CharField(blank=True, help_text='Model name (e.g. Reservation, Payment)', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_by_user', models.ForeignKey(blank=True, help_text='User who triggered this email', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'db_table': 'email_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='email_logs_status_012124_idx'), models.Index(fields=['email_type', '-created_at'], name='email_logs_email_t_6d62ae_idx'), models.Index(fields=['recipient', '-created_at'], name='email_logs_recipie_b50fb3_idx')],
            },
        ),
    ]
