# Generated by Django 5.2.13 on 2026-07-08 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_organization'),
        ('notifications', '0001_initial'),
        ('organizations', '0004_organization_latitude_organization_location_address_and_more'),
        ('payments', '0005_alter_payment_status'),
        ('reservations', '0004_cancellationrequest_processed_by'),
        ('scoring', '0002_add_org_to_match_settings'),
        ('tournaments', '0002_tournament_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_reservation', models.BooleanField(default=True)),
                ('notify_payment', models.BooleanField(default=True)),
                ('notify_tournament', models.BooleanField(default=True)),
                ('notify_equipment', models.BooleanField(default=True)),
                ('notify_account', models.BooleanField(default=True)),
                ('notify_system', models.BooleanField(default=True)),
                ('notify_message', models.BooleanField(default=True)),
                ('notify_organization', models.BooleanField(default=True)),
                ('notify_maintenance', models.BooleanField(default=True)),
                ('notify_promotion', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=False, help_text='Receive email notifications')),
                ('push_notifications', models.BooleanField(default=False, help_text='Receive browser push notifications')),
                ('sms_notifications', models.BooleanField(default=False, help_text='Receive SMS notifications')),
                ('frequency', models.CharField(choices=[('instant', 'Instant'), ('hourly', 'Hourly Digest'), ('daily', 'Daily Digest')], default='instant', max_length=10)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='read_count',
            field=models.IntegerField(default=0, help_text='Number of users who have read this'),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='recipient_count',
            field=models.IntegerField(default=0, help_text='Number of users who received this'),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='target_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='target_type',
            field=models.CharField(choices=[('all', 'All Users'), ('roles', 'Specific Roles'), ('organization', 'Specific Organization')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_text',
            field=models.CharField(blank=True, default='View Details', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, help_text='URL to redirect when clicked', max_length=500),
        ),
        migrations.AddField(
            model_name='notification',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('reservation', 'Reservation'), ('payment', 'Payment'), ('tournament', 'Tournament'), ('equipment', 'Equipment'), ('account', 'Account'), ('system', 'System'), ('message', 'Message'), ('organization', 'Organization'), ('maintenance', 'Maintenance'), ('promotion', 'Promotion')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoring.match'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.reservation'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_c4e471_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'category', '-created_at'], name='notificatio_user_id_2b1ddd_idx'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
